Bug 1948454 - Make sure the "tree-listbox" custom element is available before initializing the mail3pane. r=tobyp
This fail and fix is very similar to Bug 1947134.

Stack trace:

```
TEST-UNEXPECTED-FAIL | comm/mail/test/browser/folder-display/browser_folderPaneVisibility.js | uncaught exception
TypeError: can't access property "size", folderTree.selection is undefined at handleEvent@chrome://messenger/content/about3Pane.js:4453:11
_ensureVisibleRowsAreDisplayed@chrome://messenger/content/tree-view.mjs:1059:12
reset@chrome://messenger/content/tree-view.mjs:739:10
updateThreadItemSize@chrome://messenger/content/about3Pane.js:5034:16
async*init@chrome://messenger/content/about3Pane.js:4298:10
async*@chrome://messenger/content/about3Pane.js:168:20
async*@chrome://messenger/content/about3Pane.js:138:8
```

The intermittent fail happens when `folderTree.selection` is
undefined. However, selection is a getter for an internal Map,
which should be available as soon as a new instance of the module is
created.

I cannot find a scenario where this could happen, except when the
custom element is not yet defined. We do wait for many other custom
elements, but not for `tree-listbox`.

This patch therefore makes sure that the `tree-listbox` custom element
is defined, before executing the init code.

Differential Revision: https://phabricator.services.mozilla.com/D239317